// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_QKKD-8SGa7INnGENcRBYDNd7Fbqlz3c',
    appId: '1:888142280534:web:2cf121e3a0cc6f6014c8f7',
    messagingSenderId: '888142280534',
    projectId: 'socialapp-821f0',
    authDomain: 'socialapp-821f0.firebaseapp.com',
    storageBucket: 'socialapp-821f0.appspot.com',
    measurementId: 'G-DMCZMYFNH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz1FfUcCEywsgk-GOMIydydsL-BiygFPQ',
    appId: '1:888142280534:android:234fc06193c17c9b14c8f7',
    messagingSenderId: '888142280534',
    projectId: 'socialapp-821f0',
    storageBucket: 'socialapp-821f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsNcnYzTnhk7mdtt0x5i-mhwC0ACDn5Hs',
    appId: '1:888142280534:ios:59e6e9d0cf721c4714c8f7',
    messagingSenderId: '888142280534',
    projectId: 'socialapp-821f0',
    storageBucket: 'socialapp-821f0.appspot.com',
    iosBundleId: 'com.example.socialapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsNcnYzTnhk7mdtt0x5i-mhwC0ACDn5Hs',
    appId: '1:888142280534:ios:59e6e9d0cf721c4714c8f7',
    messagingSenderId: '888142280534',
    projectId: 'socialapp-821f0',
    storageBucket: 'socialapp-821f0.appspot.com',
    iosBundleId: 'com.example.socialapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_QKKD-8SGa7INnGENcRBYDNd7Fbqlz3c',
    appId: '1:888142280534:web:242e405bb229f13214c8f7',
    messagingSenderId: '888142280534',
    projectId: 'socialapp-821f0',
    authDomain: 'socialapp-821f0.firebaseapp.com',
    storageBucket: 'socialapp-821f0.appspot.com',
    measurementId: 'G-Z1FP3HWZ8Y',
  );
}
